apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: diogeneswallis96/backend-integrated-with-mlflow:0.0.1
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
        env:
        - name: user
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: mongo-root-username
        - name: password
          valueFrom: 
            secretKeyRef:
              name: backend-secret
              key: mongo-root-password
        - name: database
          valueFrom: 
            secretKeyRef:
              name: backend-secret
              key: mongo-root-database
        - name: mlflow_experiment
          valueFrom: 
            secretKeyRef:
              name: backend-secret
              key: mlflow-experiment

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30022
