apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit-container
        image: diogeneswallis96/streamlit-ml:1.0.0
        resources:  
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8501
        env:
        - name: URL_BACKEND
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: artifacts_url