apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit-container
        image: diogeneswallis96/streamlit-ml:1.0.0
        ports:
        - containerPort: 8501
        env:
        - name: URL_BACKEND
          valueFrom:
            configMapKeyRef:
              name: backend-configmap
              key: artifacts_url
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30024
