apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: streamlit
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30024
