version: '2.14.0'
services:
  web:
    image: backend-integrated-with-mlflow:0.0.2
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "./mlflow:/mlflow/data"
    networks:
      - ml-net
networks:
  ml-net:
    driver: bridge